site_name: Dolce Documentation
repo_url: https://github.com/dangrie158/dolce
extra_css:
  - stylesheets/extra.css
theme:
  name: material

  logo: assets/logo_compact.svg
  favicon: assets/logo_compact.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  version:
    provider: mike
    default: stable

plugins:
  - mike:
      canonical_version: stable
