name: Bump Version Number
on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: "Kind of version bump"
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  build:
    name: version bump
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          # use a recent version instead of the latest version in case
          # the latest version ever has issues that breaks publishing
          deno-version: v1.30.0

      - name: Run version bump
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          deno run --allow-read=. --allow-write=. https://deno.land/x/bmp@v0.2.0/cli.ts --${{github.event.inputs.releaseKind}}
          echo "NEW_VERSION=$(deno run --allow-read=. --allow-write=. https://deno.land/x/bmp@v0.2.0/cli.ts --info | grep "Current version:" | cut -c 23-27)" >> $GITHUB_ENV

      - name: Tag release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.RELEASE_TOKEN }}"
          tag: "v${{ env.NEW_VERSION }}"
